feat: 이메일 인증 및 회원 가입 구현
effective-tech-interview/effective-tech-interview-be pull request #2
Opened 2023-02-17 15:15 UTC by sa46lll

## 📌Linked Issues
- Resolve: #1 

## ✏Change Details
- 이메일 인증 코드 전송 `spring-boot-starter-mail`
- 이메일 인증 코드 검증
- 회원 가입
- 닉네임 랜덤 생성 `https://nickname.hwanmoo.kr`

## 💬Comment
- 이메일 인증은 일단 인증 코드 전송 기능 구현이라 텍스트 정도 들어갈 것 같아서 `SimpleMailMessage` 로 구현했습니다. 추후 html등 멀티파트 데이터 들어가게되면 `MimeMessage`로 변경하겠습니다.

## 📑References
- 

## ✅Check List

- [x] 추가한 기능에 대한 테스트는 모두 완료하셨나요?
- [x] 코드 정렬(Ctrl + Alt + L), 불필요한 코드나 오타는 없는지 확인하셨나요?

2023-02-17 15:41 UTC, be-student requested changes
일단 중요해보이는 것들은 봤는데, 추가적으로 더 확인해볼게요

2023-02-17 15:41 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
HttpCode 가 400이 맞는지, 401이 맞는지는 잘 감이 안 오긴 하네요
인증관련 부분이기에 401쪽이 더 좋을 것 같아요

2023-02-17 15:41 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/VerificationCodeMismatchException.java
> +        super(HttpStatus.BAD_REQUEST, "verification code mismatch");
HttpCode 가 400이 맞는지, 401이 맞는지는 잘 감이 안 오긴 하네요
인증관련 부분이기에 401쪽이 더 좋을 것 같아요

2023-02-17 15:41 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +@EnableAsync
gpt 쪽에도 달려있어서 이게 필요한건지 잘 모르겠어요
여기서 안 쓰면 에러가 나나요?

2023-02-17 15:41 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +    public int send(String email) {
send 라는 메서드 명은 보내는 것인데, int 타입을 리턴하는 것은 이상할 것 같아요

2023-02-17 15:41 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +        return ThreadLocalRandom.current().nextInt(100000, 999999);
```Java
private final ThreadLocalRandom
```
이렇게 바꿔주세요

2023-02-17 15:41 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/signup/dto/SignupRequest.java
> +        @Pattern(regexp = "^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$", message = "비밀번호는 영문, 숫자 조합 8자 이상입니다.")
이 패턴은 정확하게 어떤 것을 의미하는 것인가요?
그리고 regex를 사용했을 경우, 클라이언트에서 악의적으로 너무 긴 문자열을 보내면 아마 stack overflow 가 발생할텐데, 이때를 위해서 앞쪽에서 길이 검사를 했으면 좋겠어요 100글자 같은 느낌으로?

2023-02-17 15:41 UTC, be-student commented on src/main/java/com/sparcs/teamf/domain/emailauth/EmailAuth.java
> +    public static EmailAuth of(String email, Integer verificationCode) {
여기서 정적 팩토리 메서드를 사용한 이유는 무엇인가요?

2023-02-17 15:41 UTC, be-student commented on src/main/java/com/sparcs/teamf/domain/member/Member.java
> +    public static Member of(String nickname, String email, String password) {
여기서 정적 팩토리 메서드를 사용한 이유는 무엇인가요?

2023-02-17 15:51 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
저도 이 부분에서 고민했는데, 해당 에러는 클라이언트가 잘못된 요청을 보낸 경우 발생하는 에러이기 때문에 400 에러가 더 적합할 것 같습니다. (잘못된 이메일, 인증 코드 제출)
401 에러는 클라이언트가 인증되지 않았거나 인증 정보가 올바르지 않은 경우라서 보안 관련 이슈에서 사용된다고 하더라구요!

2023-02-17 15:54 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +@EnableAsync
이메일 전송이 지연 시간이 있어서 비동기로 처리하기 위해 붙인 어노테이션인데, 그래도 시간이 좀 걸리더라구요. 한번 더 확인해보겠습니다!

2023-02-17 15:54 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +    public int send(String email) {
동의합니다. 저 반환값은 난수를 service에서 저장하기 위함인데 다른 방법이 있을까요?

2023-02-17 15:59 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/signup/dto/SignupRequest.java
> +        @Pattern(regexp = "^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$", message = "비밀번호는 영문, 숫자 조합 8자 이상입니다.")
영문, 숫자 조합 8자 이상을 의미하는 정규표현식 패턴입니다.
stack overflow가 발생할 수 있다는 건 생각하지 못했네요! 앞쪽에서 길이 검사라고 하시면, length 어노테이션과 같은걸 의미하신 걸까요?

2023-02-17 16:01 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/domain/member/Member.java
> +    public static Member of(String nickname, String email, String password) {
무분별한 객체 생성을 막기 위해 만들어 주었습니다. 혹시 문제가 있을까요?

2023-02-17 16:03 UTC, be-student requested changes
추가적으로 password 가 db 에 바로 저장되는 문제가 있을 것 같네요
이 부분은 다음 pr에서 볼 수 있겠죠?

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/EmailService.java
> +public interface EmailService {
이 인터페이스를 둔 이유가 있나요?

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/signup/error/PasswordMismatchException.java
> +        super(HttpStatus.BAD_REQUEST, "password mismatch");
여기도 401이 맞을 것 같아요

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +        simpleMailMessage.setText(generateEmailContent(verificationCode));
```Java
generateEmailContent()
```
로 두고 안쪽에서 메서드를 호출하는 것이 자연스러울 것 같아요

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/dto/AuthenticateEmailRequest.java
> +        String verificationCode
int 타입으로 100000 999999 이렇게 두는게 나을 것 같아요

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/EmailAuthService.java
> +        isEmailAlreadyRegistered(email);
is 라는 메서드는 void 타입이 아니라 boolean 타입이 반환되어야 할 것 같아요
여기서 직접 에러를 던지거나, 혹은 validateAlreadyRegistered 같은 명칭으로 바꿔주세요

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/EmailAuthService.java
> +                .filter(emailAuth -> !emailAuth.getIsAuthenticated())
findFirst 인데, filter를 이용해서 체크하는 부분이 이상해보여요 바로 Optional.isPresent 같은 메서드로 체크하고 예외를 던지는 쪽이 좋을 것 같아요

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +@EnableAsync
추가로 async 메서드가 사용되지 않는 것 같아요

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/signup/service/SignupService.java
> +        Member member = Member.of(generateRandomNickname(), email, password);
generateRandomNickname() 메서드가 여기에 들어가게 되면, Transaction의 범위가 너무 커질 수 있을 것 같아요
추후에는 genereateRandomNickname() 메서드를 먼저 호출해두고, 이후에 Transactional 을 이용해 시작하는 방향으로 바꾸면 좋을 것 같아요

2023-02-17 16:03 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/signup/service/SignupService.java
> +    private String generateRandomNickname() {
하나의 메서드만 호출하는 상황에서, 이미 명칭이 명확하기에 inline 해도 좋을 것 같아요

2023-02-17 16:05 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
이 메시지가 code에 "코드" 같은 아얘 타입이 맞지 않는 요청일 경우라면 맞다고 생각하는데요
실제로 적절한 요청을 보냈는데 db 에 있는 코드와 맞지 않는다는 것을 고려했을 때 401이 더 적합하다고 생각해요

2023-02-17 16:06 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/service/EmailService.java
> +public interface EmailService {
추후 비밀번호 변경 등 다른 방식의 이메일 전송이 필요할 것으로 생각되었습니다!
인터페이스를 생략하고 구현하는 것이 좋을까요?

2023-02-17 16:06 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +    public int send(String email) {
인터페이스를 분리하든, 다른 것을 분리하든 책임이 잘못 적용된 것 같은데요
public void send(String emailAddress,int verificationCode);
이런 형태로 보내고, 안쪽에서 호출하는 것을 없애면 좋을 것 같아요

2023-02-17 16:07 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/signup/dto/SignupRequest.java
> +        @Pattern(regexp = "^(?=.*[a-zA-Z])(?=.*\\d)[a-zA-Z\\d]{8,}$", message = "비밀번호는 영문, 숫자 조합 8자 이상입니다.")
네 맞습니다

2023-02-17 16:07 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +        simpleMailMessage.setText(generateEmailContent(verificationCode));
맞네요 감사합니다!

2023-02-17 16:07 UTC, be-student commented on src/main/java/com/sparcs/teamf/domain/member/Member.java
> +    public static Member of(String nickname, String email, String password) {
생성자를 Member(String nickname,String email,String password);
형태로 만들면 이 코드는 사실 쓸데가 없는 코드같아보여서요

2023-02-17 16:10 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/EmailService.java
> +public interface EmailService {
다른 방식의 이메일 전송이 필요하다고 했을 때, 지금의 send 메서드를 재활용할 수가 없어보여요
void send(String emailAddress,String content);
같은 느낌의 범용적인 메서드로 바꾸는 방향이 좋을 것 같아요

2023-02-17 16:12 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/EmailService.java
> +public interface EmailService {
그냥 바로 service 하나만 만들면 되는데, 굳이 인터페이스도 메서드를 추가해야한다는 2중 작업이 되어버리니까요

2023-02-17 16:14 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +@EnableAsync
async 메서드로 가면 당연하지만, Transaction 이 깨진다는 것도 염두해두셔야 합니다

2023-02-18 11:17 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +    public int send(String email) {
감사합니다. 반영하겠습니다!

2023-02-19 13:52 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
말씀해주신 부분 이해되었습니다.
이 에러는 EmailAuthService의 `authenticateEmailForSignup()` 보시면, 해당 이메일이 인증 요청을 보낸 적이 없는데 클라이언트가 인증 확인 요청을 보내거나, 이미 인증된 이메일 요청에 대해 다시 보내는 경우에 호출되기 때문에 클라이언트가 적절하지 않은 요청에 대한 에러코드라고 생각했습니다.
저도 클라이언트의 적절한 요청에 대한 에러는 401이 맞다고 생각하는데 이 경우에도 적절한 요청에 대한 에러라고 생각하시는 건지 궁금합니다!

2023-02-19 14:08 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +        return ThreadLocalRandom.current().nextInt(100000, 999999);
이 경우 어떤 장점이 있는 건지 궁금합니다!
`BasicQuestionService.getRandomQuestion()`에는 기존 코드와 같이 사용되고 있는데 차이점이 있는건가요?

2023-02-19 14:40 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
emailAuth가 없을때 = 클라이언트가 인증 요청을 보내지 않고 인증 확인 요청을 보낼 때 라서 
서버 입장에서는 데이터가 없는 경우 내보내는 예외이니 401일 수도 있고, 클라이언트 입장에선 400인 것 같은데 이런 경우 어떤 에러가 우선시될까요?

2023-02-19 15:18 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
비슷한 케이스로 이미 만료된 토큰을 이용해서 요청을 보내면 401이 발생하는데요 이미 인증된 이메일 요청에 대해서 보내는 것과 유사하기에 비슷한 경우라고 생각합니다
존재하지 않는 토큰으로 요청을 보내도 비슷하게 401이 발생해야 한다고 생각하고요
서버는 서버 입장에서 최선의 예외 코드를 내려주면 좋다고 생각합니다

2023-02-19 15:23 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/service/SignupEmailService.java
> +        return ThreadLocalRandom.current().nextInt(100000, 999999);
그것도 바꿔야 될 것 같네요
ThreadLocalRandom 내부 구현을 살펴보면
![image](https://user-images.githubusercontent.com/80899085/219957329-0637313e-6592-48ae-a26b-28900eded56b.png)
이런 형태로 되어있는데요
처음에 current를 호출했을 때, seed초기화 하는 과정이 localInit 함수인데요

![image](https://user-images.githubusercontent.com/80899085/219957390-83fe1ab9-2598-4d64-8ff4-3b9c8fe68fbd.png)
실제로 이렇게 되어있는데요

![image](https://user-images.githubusercontent.com/80899085/219957405-96442408-467d-44c7-ba81-5c4a0e95c632.png)
nextInt를 사용하는 과정에서도 seed 재설정이 되기에, 내부에서 중복 설정이 됩니다

만약 조금 더 안전한 암호를 원하신다면 SecureRandom 쪽을 사용하는 것도 좋아보이네요

2023-02-19 15:24 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
서버와 클라이언트 에러가 모호하여 예외 클래스를 다시 정의하였습니다. 확인 부탁드립니다!

2023-02-19 15:29 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/VerificationCodeMismatchException.java
> +        super(HttpStatus.BAD_REQUEST, "verification code mismatch");
클라이언트가 인증 코드를 다르게 입력했을 때 호출되는 예외 클래스라서 클라이언트 요청이 오류로 인한 400 에러 상태코드가 아닐까요?

2023-02-19 15:34 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/domain/member/Member.java
> +    public static Member of(String nickname, String email, String password) {
new로 객체 생성을 말씀하시는 거죠? 저의 짧은 지식으로는 생성자를 통한 직접적인 객체 생성보다 메서드를 통한 객체 생성이 낫다고 알고 있습니다!
정적팩토리 메서드는 매번 새로운 객체를 생성할 필요가 없다는 점과 캡슐화에 대한 장점이 있습니다.
혹시 어떤 이유에서 생성자를 통한 객체 생성이 낫다고 생각하시는지 알 수 있을까요?

2023-02-19 15:35 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/service/EmailService.java
> +public interface EmailService {
`void sent()`로 재활용할 수 있도록 변경하였습니다!

2023-02-19 15:36 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/signup/error/PasswordMismatchException.java
> +        super(HttpStatus.BAD_REQUEST, "password mismatch");
이 곳도 클라이언트 오류라고 생각됩니다!

2023-02-19 15:36 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/signup/error/PasswordMismatchException.java
> +        super(HttpStatus.BAD_REQUEST, "password mismatch");
이 곳도 클라이언트 요청으로 인한 오류라고 생각됩니다!

2023-02-19 15:37 UTC, be-student reviewed
궁금한 점은 남겼는데요 
아직 코멘트 남겼던 것들에 대해서 답이 안 달린 것도 많고, 너무 파일이 많이 바뀌어서 어디서부터 어디까지 리뷰를 남겨야 하는지 잘 감이 안오네요

2023-02-19 15:37 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/EmailVerificationExpiredException.java
> + */
이 케이스는 메일을 여러개 보내주는게 맞지 않을까요? 
메일이 스팸으로 갔는지, 뭔지 모르는 상황에서 재전송을 요구할 수도 있으니까요

2023-02-19 15:37 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/signup/service/SignupService.java
> +        isEmailVerified(email);
여기도 boolean 타입을 리턴하도록 바꿔주시면 좋을 것 같아요

2023-02-19 15:41 UTC, sa46lll commented
> 궁금한 점은 남겼는데요 아직 코멘트 남겼던 것들에 대해서 답이 안 달린 것도 많고, 너무 파일이 많이 바뀌어서 어디서부터 어디까지 리뷰를 남겨야 하는지 잘 감이 안오네요

아직 코드리뷰 반영 중이라 기다려 주시면 감사하겠습니다.

2023-02-19 15:43 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/VerificationCodeMismatchException.java
> +        super(HttpStatus.BAD_REQUEST, "verification code mismatch");
https://github.com/effective-tech-interview/effective-tech-interview-be/pull/2#discussion_r1111259202
이것과 비슷하다고 생각합니다

2023-02-19 15:48 UTC, be-student commented
혹시 그러면 제가 언제쯤 확인하면 될까요?

2023-02-19 15:49 UTC, sa46lll commented
> 혹시 그러면 제가 언제쯤 확인하면 될까요?

새벽에 모두 수정할 예정이라 내일 중으로 확인해주시면 될 것 같습니다.

2023-02-19 15:59 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
InvalidEmailOrVerificationCodeException -> EmailRequestRequiredException, EmailVerificationExpiredException 예외 클래스로 변경해주었습니다.

2023-02-19 16:00 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
InvalidEmailOrVerificationCodeException -> EmailRequestRequiredException, EmailVerificationExpiredException 예외 클래스로 변경해주었습니다. 일단 인증 관련은 모두 401로 통일해야 한다고 생각하시는게 맞을까요?

2023-02-19 16:06 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/domain/emailauth/EmailAuth.java
> +    public static EmailAuth of(String email, Integer verificationCode) {
아래 내용과 같습니다!

2023-02-19 16:13 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/InvalidEmailOrVerificationCodeException.java
> +        super(HttpStatus.BAD_REQUEST, "this email does not exist or the verification code has already been verified.");
네 저는 그렇게 생각해요

2023-02-19 16:16 UTC, be-student commented on src/main/java/com/sparcs/teamf/domain/member/Member.java
> +    public static Member of(String nickname, String email, String password) {
쓰는 입장에서 생각했을 때, 가장 처음 생각나는 객체 생성 방법은 당연하지만 생성자로 생성하는 것이고, 가려져있기 때문에, 정의로 와서 어떤 메서드로 생성할 수 있는지를 체크하는 과정을 거쳐야 하고요
클래스 작성자의 입장에서도 생각해보면 그냥 생성자만 만들면되는데, 정적 팩토리메서드까지 만들어야 하니까요

분명히 객체를 새롭게 만들지 않아도 되는 케이스나, 상위타입의 인스턴스로 반환시키거나 하는 여러가지 방식은 알지만, 이 경우에서는 장점이 전혀 사용되지 않는 케이스라고 생각해서 그냥 여쭤본거였어요
쓰고싶다면 써도 괜찮다고 생각하기는 합니다

2023-02-19 16:26 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/EmailVerificationExpiredException.java
> + */
여러개 보낸다는게 어떤 의미일까요?
만료된 인증에 대해 인증 요청을 할 때, 추가적으로 메일을 알아서 보내야 한다고 하시는 걸까요?

2023-02-19 16:33 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/EmailVerificationExpiredException.java
> + */
아하 앞부분 주석을 보고서 이해를 잘못했던 것 같네요

이 에러가 발생하는 정확한 경우가 제가 이해한 부분이 맞다면 인증은 성공했고, 같은 코드로 2번째 요청이 왔을 때 발생할 것으로 보이는데요
사용자가 연속해서 2번 전송버튼을 눌렀을 때, 클라이언트가 2번째 것은 실패라고 받아들이고, 실패로 처리할 수 있을테니 이 검증은 없는 부분이 맞는 것 같아요
이미 인증되었다면 검사하는 과정 대신 바로 통과하는 방향이 더 적절할 것 같아요

2023-02-19 16:37 UTC, sa46lll commented
> 추가적으로 password 가 db 에 바로 저장되는 문제가 있을 것 같네요 이 부분은 다음 pr에서 볼 수 있겠죠?

네네 `spring security` 라이브러리의 `BCryptPasswordEncoder` 암호화 방식을 쓸 예정이라 다음 pr애서 구현하도록 하겠습니다.

2023-02-19 16:42 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/EmailVerificationExpiredException.java
> + */
아하 그런가요?
유저 관점에서 인증 단계까지만 완료하고 앱을 재접속하는 경우에 해당 인증코드 요청을 하지 않고 바로 인증코드 검증 단계로 가도 괜찮다고 하시는걸까요? 제 경험상 일반적으로 재접속시에 인증을 다시 받는 플로우가 잦았던 것 같아서요!

2023-02-19 16:42 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/EmailVerificationExpiredException.java
> + */
오 그런가요?
유저 관점에서 인증 단계까지만 완료하고 앱을 재접속하는 경우에 해당 인증코드 요청을 하지 않고 바로 인증코드 검증 단계로 가도 괜찮다고 하시는걸까요? 제 경험상 일반적으로 재접속시에 인증을 다시 받는 플로우가 잦았던 것 같아서요!

2023-02-19 16:52 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/EmailVerificationExpiredException.java
> + */
인증단계 완료후 재접속 했을 경우에, 인증코드를 새로 요청해야되는 부분은 당연히 맞다고 생각하는데요
성공적인 요청을 2번 보내면, 2번째는 실패 처리가 되는 부분이 좋은 흐름은 아닐것 같다는 부분인데요

뭔가의 이유로 123456이라는 코드가 성공적으로 2번보내졌을 때, 클라이언트가 400을 받게 되는데, 이러면 인증을 성공했음에도 실패했다는 결과가 나올 것 같아서, 이 검증은 제거하는 방향이 가장 좋아보일 것 같아보여요

2023-02-19 17:10 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/emailauth/error/EmailVerificationExpiredException.java
> + */
네네 동의합니다. 이 검증 로직은 삭제하겠습니다!
그렇다면 혹시 유효한 인증을 2번 했을 때와 재접속 후 인증을 다시 했을 때의 구분은 어떻게 두는게 좋을까요?
이 검증을 없애게 되면 재접속 후의 인증도 통과가 될텐데, 제가 생각한 방법으로는 재접속시 인증 요청 -> 인증 확인할 수 있도록 프론트쪽에서 막아주는 방법 정도 생각되는데 괜찮을까요?

2023-02-19 17:15 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/emailauth/error/EmailVerificationExpiredException.java
> + */
네 그 정도면 충분하다고 생각해요
백엔드에서 그것을 알 방법도 없고, 처리할 필요도 없을 것 같아요

2023-02-20 02:56 UTC, merged