feat: 페이지 질문 리스트 조회 기능 구현
effective-tech-interview/effective-tech-interview-be pull request #40
Opened 2023-03-17 00:37 UTC by sa46lll

## 📌Linked Issues
- Resolve: #35 

## ✏Change Details
- 페이지 질문 리스트 조회
- gpt 내부 로직 변경

## 💬Comment
- gpt 내부 로직은 기존에 쓰지 않는 메서드를 변경하였습니다.
- 동기화로 변경하였는데, 생각보다 시간이 오래 걸리더라구요. 많이 호출될 일은 없겠지만, 한번 논의해 보아야 할 것 같습니다!

## 📑References
- 

## ✅Check List

- [ ] 추가한 기능에 대한 테스트는 모두 완료하셨나요?
- [x] 코드 정렬(Ctrl + Alt + L), 불필요한 코드나 오타는 없는지 확인하셨나요?

2023-03-17 08:38 UTC, be-student requested changes
리뷰가 늦었네요 혹시 더 자세하게 알려주실 수 있으신가요?

2023-03-17 08:38 UTC, be-student commented on src/main/java/com/sparcs/teamf/domain/page/Page.java
> +@NoArgsConstructor
이 부분은 왜 있는건가요?

2023-03-17 08:38 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    private Question[] getQuestionGroup(Question basicQuestion) {
이 부분은 List 형태로 받으면 어떨까요

2023-03-17 08:38 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +            .orElseThrow(MemberNotFoundException::new);
여기서 memberId 를 사용하는 이유가 뭔가요?

2023-03-17 08:38 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
이 부분은 아닌 것 같아요
있다고 다 채우는 방향이 아니라, 초기에는 1개만
그 다음에는 2개만
순서로 쭉 진행해야 할 것 같아요

2023-03-17 09:05 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/domain/page/Page.java
> +@NoArgsConstructor
서비스 쪽에서 기본 생성자 호출을 해야 해서 변경해주었습니다.
저도 고민을 좀 해봤는데 다른 방법이 마땅히 생각나지 않아서요 혹시 좋은 방법이 있을까요?

2023-03-17 09:07 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    private Question[] getQuestionGroup(Question basicQuestion) {
항상 4 크기의 데이터가 들어가서 배열로 선언해주었습니다. 하나씩 삽입하기에도 배열이 더 낫다고 생각했는데 혹시 리스트로 받았을 때의 장점이 있을까요?

2023-03-17 09:08 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +            .orElseThrow(MemberNotFoundException::new);
page에 memberId를 넣어주기 위함입니다!

2023-03-17 09:56 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
다 채우는 방향이 아니라는게 어떤 의미인가요?

2023-03-17 15:28 UTC, be-student requested changes
혹시 생성자에서 초기화를 미리 할 수 있을까요?

2023-03-17 15:28 UTC, be-student commented on src/main/java/com/sparcs/teamf/domain/page/Page.java
> +@NoArgsConstructor
이 부분은 이런 느낌으로 진행된다면...?
```
public Page(Member member, List<PageQuestion>){

}
```
같은 형태로 미리 채우는 방식으로 전체의 불변식을 지킬 수 있을 것 같아요

이렇게 되면 setter 가 제거될 수 있으니까요

2023-03-17 15:28 UTC, be-student commented on src/main/java/com/sparcs/teamf/domain/page/PageQuestion.java
> +    }
이런 부분도, updatePage 대신, 한번에 생성자에서 받아서 초기화 가능할까요?
안정성 측면에서 불변을 보장할 수 있을 것 같아요

2023-03-17 15:28 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
미리 1~4까지가 저장되어 있다는 경우라면요
처음에는 1번만 보여주고,
2번째는 2번까지만 보여주고
3번째는 3번까지만 보여주고
4번째는 4번까지만 보여줘야됩니다

지금같은 경우는 제가 정확하게 봤는지 모르겠지만
1 ~ 4번이 저장되어있는 경우에
1 ~ 4번까지 미리 저장해서 한꺼번에 전달하고 있는 것 같아서요

2023-03-17 15:28 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    private Question[] getQuestionGroup(Question basicQuestion) {
배열과, List 의 차이를 생각해보면 단순하게 삽입, 제거를 하는 과정은 동일하게 가능한데요
하나씩 삽입하기도 당연하지만 별 차이가 없죠
Array 형태로 반환된다면, 추후에 만약 5개까지 가능하도록 변경되었을 경우에, 숫자를 직접 변환해야하는데,, 그런 과정이 없어질 것 같아요

2023-03-17 15:41 UTC, signature-hyeon commented on src/main/java/com/sparcs/teamf/domain/page/Page.java
> +@NoArgsConstructor
그렇다면 pageQuestion이 먼저 생성하고, page를 후에 생성해야할 것 같은데 pageQuestion에 pageId가 들어가야해서  pageQuestion의 모든 pageId를 업데이트 해줘야 할 것 같기도 합니다 😥

2023-03-17 15:45 UTC, signature-hyeon commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    private Question[] getQuestionGroup(Question basicQuestion) {
흠 리스트로 변경해도 괜찮을 것 같긴 하지만 질문의 개수가 달라져도 모두 통일되게 변경되지 않을까 싶어서 고민되네요.. 혹시 질문의 개수를 전역상수 느낌으로 관리하는 것은 어떨까요?

2023-03-17 15:47 UTC, signature-hyeon commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
응답만 모든 데이터를 보여주고 있고, 저장은 말씀하신대로 1번만 저장되고 있습니다 :)
유저 답변 시에 하나씩 데이터 생성이 들어갈 것 같습니다!

2023-03-17 16:07 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/domain/page/PageQuestion.java
> +    }
오 좋네요! 생각을 못해줬어요. page 클래스도 마찬가지로 변경하면 기본 생성자 없이도 변경 가능할 것 같습니다. 감사합니다 :)

2023-03-17 16:14 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/domain/page/Page.java
> +@NoArgsConstructor
밑의 코멘트 반영해서 기본 생성자 없이도 구현 가능할 것 같습니다! 감사합니다.

2023-03-18 03:46 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
아뇨아뇨
질문 자체를 하나씩만 등록해야돼요
지금은 미리 모든 질문들을 다 등록해주는 건데요
질문 자체도 한번만 등록되어야 해요

2023-03-18 03:55 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
질문은 basicQuestion 하나만 저장되고 있습니다. 혹시 확인해보셨을까요?

2023-03-18 04:28 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
```
  for (int i = 1; i < 3; i++) {
            Question parentQuestion = questionGroup[i];
            List<Question> questionByParentQuestionId = questionRepository.findQuestionByParentQuestionId(parentQuestion.getId());
            if (questionByParentQuestionId.isEmpty()) {
                Question question = gpt.loadNextQuestion(parentQuestion);
                questionGroup[i + 1] = question;
                return questionGroup;
            }
            questionGroup[i + 1] = questionByParentQuestionId.get(0);
        }
```
를 보게 되면
지금은 처음 id 를 가지고 처음부터 끝까지 미리 다 로딩을 해놓는데요
이 과정이 여기에 있으면 안된다고 생각해요
기본 질문이기에, 가장 처음 질문 하나만을 로딩해야 하고, 그 밖에 다른 것들은 필요 없어보여요

```
   List<QuestionResponse> questionResponses = Arrays.stream(questionGroup)
            .map(QuestionResponse::from)
            .toList();

        Page page = new Page();
        PageQuestion pageQuestion = new PageQuestion(basicQuestion);
        pageQuestion.updatePage(page);
        page.updateMember(member);
        Page savedPage = pageRepository.save(page);
        return new QuestionsResponse(savedPage.getId(), questionResponses);
```
이 부분도 처음 요청한 한개의 질문에 대해서만 답변을 보내주는 게 맞을 것 같아요

[basicQuestion]
이것만 보내주면 될 것 같아요

2023-03-18 04:28 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    private Question[] getQuestionGroup(Question basicQuestion) {
그것도 쓰이는 곳이 많다면 괜찮을 것 같은데요
```
    List<QuestionResponse> questionResponses = Arrays.stream(questionGroup)
            .map(QuestionResponse::from)
            .toList();
```

실제로 반환되는 경우를 보면
바로 List 형태로 map 을 사용해서 쓰는데요
배열을 반환해서 Arrays.stream()을 통해서 쓸 이유가 그렇게 많지 않아보여요

개인 취향이긴 한데요
솔직히 말해서 배열을 사용해서 얻을 수 있는 장점이 단 한가지도 없어보여요
List 대신 배열로 했을 때, 얻을 수 있는 장점은 몇바이트의 메모리 사용 효율?
몇 나노초 정도에 대한 성능 정도가 있을 텐데요

솔직히 그런 성능을 바라고 코딩을 하는 느낌은 아니다보니, 성능상의 저런 이점을 고려하는 것은 아닐 것 같고요
유연성을 생각해보면, 배열보다는 무조건 List 가 더 좋다고 생각합니다

쓸수 있는 기능들이 정말 많은 상황에서, 그걸 포기하고 얻는 장점이 없어보였어요
가독성 차이도 없고요

2023-03-18 04:34 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
아 뭔가 기획에 대한 소통에 오해가 있었던것같네요!
말씀하신대로 나눠서 받게되면 아예 api가 나누어질 것 같습니다. 처음에 일반질문 조회할땐 page 없이 get 요청이 들어올 것이고 꼬리질문조회할땐 page 를 받아야해서요. 동일하게 생각하실까요?

2023-03-18 04:37 UTC, be-student commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    }
네 맞아요
정확해요

2023-03-18 04:37 UTC, sa46lll commented on src/main/java/com/sparcs/teamf/api/question/service/PageQuestionService.java
> +    private Question[] getQuestionGroup(Question basicQuestion) {
그렇군요 수정하겠습니다! 감사합니다 :)

2023-03-19 04:33 UTC, be-student approved these changes
동작 다 확인 했어요
maximum number of tail questions exceed 예외 제거해주신 것도 너무 좋았어요

2023-03-19 05:36 UTC, merged