refactor: 이메일 인증 데이터 캐시로 관리
effective-tech-interview/effective-tech-interview-be pull request #65
Opened 2023-05-09 10:56 UTC by sa46lll

## 📌Linked Issues
- Resolve: #59
- Resolve: #60

## ✏Change Details
- 이메일 인증 데이터 캐시로 관리
- Event enum 클래스를 domain-redis 모듈로 위치 변경

## 💬Comment
- 멀티 모듈 적용하면서 exception이 모두 RuntimeException으로 바뀌었던데, 이 부분 todo인가요? 일단 다른 예외들과 동일하게 처리해두었습니다!

## 📑References
- 

## ✅Check List

- [x] 추가한 기능에 대한 테스트는 모두 완료하셨나요?
- [x] 코드 정렬(Ctrl + Alt + L), 불필요한 코드나 오타는 없는지 확인하셨나요?

2023-05-09 15:34 UTC, be-student requested changes
잘 읽었습니다! 💯 
일단 질문만 좀 남겨뒀어요!
다 의도하신게 맞다고 하시면 다시 리뷰 요청 보내주시면 approve 할게요 ㅎㅎ

2023-05-09 15:34 UTC, be-student commented on auth/src/main/java/com/sparcs/teamf/email/EmailKeyBuilder.java
> +        return String.format(EMAIL_KEY_FORMAT, email, event);
이벤트도 겹치고, email 도 겹치면, 덮어씌워지게 되는 것 같은데 이 부분을 의도하신게 맞나요?
실수로 2번 클릭해서 2번 요청이 날아왔을 때, 기존에는 처음꺼를 입력했어도 괜찮도록 한 것 같아서요!

2023-05-09 15:34 UTC, be-student commented on auth/src/main/java/com/sparcs/teamf/exception/EmailSendLimitExceededException.java
> +     */
https://github.com/effective-tech-interview/effective-tech-interview-be/issues/64
이 부분에 HttpStatus 를 사용하지 않는 이유를 달아두고, 앞으로 어떻게 바뀔 것 같은지도 달아뒀어요!
보시고 괜찮으면 커멘트 달아주시면 좋을 것 같아요!

2023-05-09 15:34 UTC, be-student commented on auth/src/main/java/com/sparcs/teamf/service/EmailAuthService.java
> +        checkIfEmailAlreadySent(emailKey);
1시간에 1번만 이메일을 발송할 수 있도록 해주신 것 같네요 
저번에 1사람당 하루에 5번씩 발송할 수 있도록 제한한다고 하시지 않으셧나요?? 바뀌신 이유가 있는지 궁금해요

2023-05-10 05:34 UTC, signature-hyeon commented on auth/src/main/java/com/sparcs/teamf/email/EmailKeyBuilder.java
> +        return String.format(EMAIL_KEY_FORMAT, email, event);
키 구성은 말씀해주신게 맞고, checkIfEmailAlreadySent 메서드에서 한 시간에 한번만 호출되도록 예외 처리를 해주고 있기 때문에 덮어 쓰는 것을 방지했습니다!
(기존의 코드도 가장 마지막 인증 번호와 일치되도록 검증했었어요! 아마 data-jpa의 OrderByCreatedDateDesc 사용했을 거예요)
혹시 더 나은 방법이 있다면 말씀부탁드려요! 😊

2023-05-10 05:34 UTC, sa46lll commented on auth/src/main/java/com/sparcs/teamf/exception/EmailSendLimitExceededException.java
> +     */
확인했습니다! 제가 놓친 부분이네요 많이 배워갑니다!!

2023-05-10 05:34 UTC, sa46lll commented on auth/src/main/java/com/sparcs/teamf/service/EmailAuthService.java
> +        checkIfEmailAlreadySent(emailKey);
저도 이 부분에서 고민을 좀 했는데, 둘 다 제한이 목적이라면 redis의 ttl 기능을 더 적절하게 사용하기에는 이 방법이 더 좋아 보였어요! 그때 둘 중 어떤 걸로 해도 크게 상관없다고 하셨던 것 같아서 이렇게 구현해보았습니다!

2023-05-11 00:49 UTC, be-student approved these changes
좋아요
너무 잘 봤어요
고생 많으셨어요!! :100:

2023-05-11 00:49 UTC, merged